<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Sveriges Kommuner och Regioner licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->		
<wsdl:definitions name='GetListingCountyInteraction' xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:tjsr='urn:riv:supportprocess:logistics:carelisting:GetListingCountyResponder:2' xmlns:tjsi='urn:riv:supportprocess:logistics:carelisting:GetListingCountyInitiator:2' xmlns:tns='urn:riv:supportprocess:logistics:carelisting:GetListingCounty:2:rivtabp21' targetNamespace='urn:riv:supportprocess:logistics:carelisting:GetListingCounty:2:rivtabp21' xmlns:itr='urn:riv:itintegration:registry:1'>
  <wsdl:documentation>
		Tjänsteinteraktionens namn: GetListingCountyInteraction
		Beskrivning: 
		  Hämta invånares aktuella listningsregion
		Revisioner: 
		Tjänstedomän: supportprocess:logistics:carelisting
		Tjänsteinteraktionstyp: Fråga-Svar
		WS-profil: RIVTABP21
		Förvaltas av: Sveriges Kommuner och Regioner
		</wsdl:documentation>
  <wsdl:types>
    <xs:schema targetNamespace='urn:riv:supportprocess:logistics:carelisting:GetListingCounty:2:rivtabp21'>
      <xs:import schemaLocation='GetListingCountyResponder_2.0.xsd' namespace='urn:riv:supportprocess:logistics:carelisting:GetListingCountyResponder:2' />
      <xs:import schemaLocation='../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
    </xs:schema>
  </wsdl:types>
  <wsdl:message name='GetListingCountyRequest'>
    <wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
      <wsdl:documentation>The organisation number of the receiving insurance institution</wsdl:documentation>
    </wsdl:part>
    <wsdl:part name='parameters' element='tjsr:GetListingCounty' />
  </wsdl:message>
  <wsdl:message name='GetListingCountyResponse'>
    <wsdl:part name='parameters' element='tjsr:GetListingCountyResponse' />
  </wsdl:message>
  <wsdl:portType name='GetListingCountyResponderInterface'>
    <wsdl:operation name='GetListingCounty'>
      <wsdl:input message='tns:GetListingCountyRequest' />
      <wsdl:output message='tns:GetListingCountyResponse' />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name='GetListingCountyResponderBinding' type='tns:GetListingCountyResponderInterface'>
    <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
    <wsdl:operation name='GetListingCounty'>
      <soap:operation soapAction='urn:riv:supportprocess:logistics:carelisting:GetListingCountyResponder:2:GetListingCounty' style='document' />
      <wsdl:input>
        <soap:header use='literal' message='tns:GetListingCountyRequest' part='LogicalAddress' />
        <soap:body use='literal' parts='parameters' />
      </wsdl:input>
      <wsdl:output>
        <soap:body use='literal' />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name='GetListingCountyResponderService'>
    <wsdl:port name='GetListingCountyResponderPort' binding='tns:GetListingCountyResponderBinding'>
      <soap:address location='http://tempuri.org' />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>