<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. Inera AB licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->    
<wsdl:definitions name='SearchPersonsForProfileByOrderInteraction'
    xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
    xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
    xmlns:xs='http://www.w3.org/2001/XMLSchema'
    xmlns:tjsr='urn:riv:strategicresourcemanagement:persons:person:SearchPersonsForProfileByOrderResponder:5'
    xmlns:itr='urn:riv:itintegration:registry:1'
    xmlns:tns='urn:riv:strategicresourcemanagement:persons:person:SearchPersonsForProfileByOrder:5:rivtabp21'
    targetNamespace='urn:riv:strategicresourcemanagement:persons:person:SearchPersonsForProfileByOrder:5:rivtabp21'>

    <wsdl:documentation>
         Tjänsteinteraktionens namn: SearchPersonsForProfileByOrder
         Beskrivning: 
           Tjänst för att asynkront söka uppgifter för 0..* personidentiteter utifrån sökparametrar definierad enligt en bestämd syntax. 
           Denna tjänst tillskillnad från SearchPersonsForProfile returnerar endast ett orderId som sedan ska användas tillsammans med tjänsten GetFilesForOrderId för att få tillgång till resultatet av sökningen. Se sekvensschemat i kapitel 3.1.9.
           Ett typiskt användningsfallet för denna tjänst är när man önskar få ut ett större antal personuppgifter baserat på sökparametrarna. T.ex för en screeningverksamhet (ex screening av bröstcancer) att kunna ta ut en population personer baserat på ålder, kön och län för att kalla dem till undersökning.
         Revisioner: 
         Tjänstedomän: strategicresourcemanagement:persons:person
         Tjänsteinteraktionstyp: Fråga-Svar
         WS-profil: RIVTABP21
         Förvaltas av: Inera AB
    </wsdl:documentation>
    
    <wsdl:types>
        <xs:schema targetNamespace='urn:riv:strategicresourcemanagement:persons:person:SearchPersonsForProfileByOrder:5:rivtabp21'>
            <xs:import schemaLocation='SearchPersonsForProfileByOrderResponder_5.0.xsd' namespace='urn:riv:strategicresourcemanagement:persons:person:SearchPersonsForProfileByOrderResponder:5' />
            <xs:import schemaLocation='../../core_components/itintegration_registry_1.0.xsd' namespace='urn:riv:itintegration:registry:1' />
        </xs:schema>
    </wsdl:types>
    
        
    <wsdl:message name='SearchPersonsForProfileByOrderRequest'>
        <wsdl:part name='LogicalAddress' element='itr:LogicalAddress'>
            <wsdl:documentation>http://tempuri.org</wsdl:documentation>
        </wsdl:part>
    
        <wsdl:part name='parameters' element='tjsr:SearchPersonsForProfileByOrder' />
    </wsdl:message>

    <wsdl:message name='SearchPersonsForProfileByOrderResponse'>
        <wsdl:part name='parameters' element='tjsr:SearchPersonsForProfileByOrderResponse' />
    </wsdl:message>

    <wsdl:portType name='SearchPersonsForProfileByOrderResponderInterface'>
        <wsdl:operation name='SearchPersonsForProfileByOrder'>
            <wsdl:input message='tns:SearchPersonsForProfileByOrderRequest' />
            <wsdl:output message='tns:SearchPersonsForProfileByOrderResponse' />
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name='SearchPersonsForProfileByOrderResponderBinding' type='tns:SearchPersonsForProfileByOrderResponderInterface'>
        <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http' />
        <wsdl:operation name='SearchPersonsForProfileByOrder'>
            <soap:operation soapAction='urn:riv:strategicresourcemanagement:persons:person:SearchPersonsForProfileByOrderResponder:5:SearchPersonsForProfileByOrder' style='document' />
            <wsdl:input>
                <soap:header use='literal' message='tns:SearchPersonsForProfileByOrderRequest' part='LogicalAddress' />
                <soap:body use='literal' parts='parameters' />
            </wsdl:input>
            <wsdl:output>
                <soap:body use='literal' />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name='SearchPersonsForProfileByOrderResponderService'>
        <wsdl:port name='SearchPersonsForProfileByOrderResponderPort' binding='tns:SearchPersonsForProfileByOrderResponderBinding'>
            <soap:address location='http://tempuri.org' />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
